spring:
#  datasource:
#    url: jdbc:mysql://localhost/test
#    username: dbuser
#    password: dbpass
#    driver-class: com.mysql.jdbc.Driver


# Server settings (ServerProperties)
server:
  port: 8088
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /api

# Tomcat specifics
tomcat:
  accessLogEnabled: false
  protocolHeader: x-forwarded-proto
  remoteIpHeader: x-forwarded-for
  basedir:
  backgroundProcessorDelay: 30 # secs

logging:
  level:
    org.springframework.web: DEBUG
